### ISSUE TITLE
The action should run eslint for all files if `.eslintrc` is among of the changed files

### ISSUE THREAD

**Issue by owanturist** [sibiraj-s/action-eslint#11]
Hi there,

Thank you for creating such a nice github action! It works pretty smoothly except when the `.eslintrc` file appears among the changed ones. In the worst-case scenario, it does not run eslint at all (when only the rc file is changed, like enabling a new rule), in the best case it runs only on changed files and might miss some potential eslint rules violations.

Do you think it would make sense to run eslint for all (respecting the listed extensions in the github action) files in case `.eslintrc` is changed? It might complicate the flow a bit by the fact that `.eslintrc` might have a variety of extensions like `.eslintrc.json`, `.eslintrc.js` or just `.eslintrc`

**Comment by sibiraj-s** [comment]
Hi.

Thank you and thanks for creating this issue. I am not sure why that happens. I'll have to check. Do you have any reproducible repo?

Also, I have some thoughts let me debug some more on whats happening before answering to this.

**Comment by sibiraj-s** [comment]
Just read that `.eslintrc` config file is deprecated a long back, at-least 4 years back. May be eslint doesn't do a great job with that? 🤔 Or do you have issues with eslintrc without extension as well?

**Comment by sibiraj-s** [comment]
May be I can add an option for config file

```yaml
      - uses: sibiraj-s/action-eslint@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
          config-file: .eslintrc.json
```

Will this fix the issue?

**Comment by sibiraj-s** [comment]
I misunderstood the issue earlier. Running the entire eslint is a easy thing, but things might complicate when its included in this plugin as that was never its intention

The following might help?

```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          eslintrc:
            - '.eslintrc*'

    # run eslint on entire directory if eslintrc is changed
    - name: Run eslint
      if: steps.filter.outputs.eslintrc == 'true'
      run: npx eslint .

    # run eslint on changed files
    - name: Run eslint on changed files
      if: steps.filter.outputs.eslintrc == 'false'
      uses: sibiraj-s/action-eslint@v2
```
