### ISSUE TITLE
all-files is default in V3

### ISSUE THREAD

**Issue by StefanSchoof** [sibiraj-s/action-eslint#12]
I upgraded to this action V3 and the all-files does not work as I expected it.

This is the config we are using

```yaml
     - uses: sibiraj-s/action-eslint@58865e4bdd90058b20fe485b3354b6d80cb99e9f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          annotations: true
          eslint-args: "--config frontend/.eslintrc.yml"
          extensions: "js,jsx,ts,tsx"
          working-directory: "frontend"
```

Add this is the output we are getting:

```
Run sibiraj-s/action-eslint@58865e4bdd90058b20fe485b3354b6d80cb99e9f
  with:
    token: ***
    annotations: true
    eslint-args: --config frontend/.eslintrc.yml
    extensions: js,jsx,ts,tsx
    working-directory: frontend
    all-files: false
Linting all files.
...
```

I do not understand why `Linting all files.` is written, when `all-files` is false. Also setting `all-files` in with to `false` is not changing anything.

https://github.com/sibiraj-s/action-eslint/blob/58865e4bdd90058b20fe485b3354b6d80cb99e9f/src/get-files.ts#L10-L13
