### ISSUE TITLE
Error: couldn't find the config "airbnb" to extend from

### ISSUE THREAD

**Issue by SergioInToronto** [sibiraj-s/action-eslint#19]
When I format my whole codebase I'm getting this error:

`ESLint couldn't find the config "airbnb" to extend from. Please check that the name of the config is correct.`

<img width="969" alt="image" src="https://github.com/sibiraj-s/action-eslint/assets/66286679/45e613d1-0f06-44f0-b25b-9cfebeef507c">

**My Config**
```yaml
      - name: Lint
        uses: sibiraj-s/action-eslint@v3
        with:
          eslint-args: '--report-unused-disable-directives --max-warnings 1333 --ignore-path=.gitignore'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
          all-files: true
```

I searched around but couldn't find a reason why it's happening. The step before runs `npm install` so all the dependencies should be there. Running `eslint` with the same args locally works as expected. What could be happening?
