### ISSUE TITLE
Module not found in subdirectory

### ISSUE THREAD

**Issue by blasdfaa** [sibiraj-s/action-eslint#7]
I get this error every time
```
client/src/util/token.js --ignore-path=.gitignore --quiet
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/home/runner/work/online-shop/online-shop/node_modules/eslint/bin/eslint'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:[77](https://github.com/Zer0S2m/online-shop/runs/6698144246?check_suite_focus=true#step:5:80)8:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Error: The process '/opt/hostedtoolcache/node/16.15.0/x64/bin/node' failed with exit code 1
```

My yml file
```
name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/lint.yaml"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - uses: sibiraj-s/action-eslint@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          eslint-args: "--ignore-path=.gitignore --quiet"
          extensions: "js,jsx,ts,tsx"
          annotations: true
```

repo structure
![image](https://user-images.githubusercontent.com/72477415/171505931-eb753794-4e8b-4cc2-b848-2d720ffda97f.png)

**Comment by sibiraj-s** [comment]
<img width="799" alt="Screenshot 2022-06-04 at 8 51 43 AM" src="https://user-images.githubusercontent.com/20282546/171978523-d215d2bd-f15e-4a55-b46a-7f4253429ff6.png">

the working directory applies only to run path. Since the root is non node env. Can you try adding `bin-path` manually?

**Comment by sibiraj-s** [comment]
I hope this will fix the issue. Please re-open if it doesn't

**Comment by abenhamdine** [comment]
I reopen this issues because I have this exact same problem, and bin-path does not solve it.  
I don't even understand what bin-path is expected to do because it doesn't seem to exist in this action.

<img width="649" alt="image" src="https://github.com/sibiraj-s/action-eslint/assets/7466144/711c6457-1ce7-4c58-970c-491ab4afa820">


My workflow : 
```yml
name: Lint
on:
  pull_request:
    types: [ready_for_review]
defaults:
  run:
    working-directory: ./client
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node version
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: ⬇️ Checkout branch
      uses: actions/checkout@v4
    - name: Eslint
      uses: sibiraj-s/action-eslint@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        eslint-args: '--config .eslintrc.json'
        extensions: 'ts,tsx'
        annotations: true
        working-directory: client
        bin-path: "client/node_modules/eslint/bin"
```
