### ISSUE TITLE
Action is running Eslint in folders not specifed

### ISSUE THREAD

**Issue by thirdeyeclub** [sibiraj-s/action-eslint#9]
I am using this action on a mono repo. Both the client and server run from their various places in /packages. Each have Eslint inside of them. While trying to debug some code I decided to comment out the action Lint API package to avoid an eslint error that I did not want to deal with at the momment. But when I disabled the first action the second action (which should be running in ./packages/ui/.eslintrc.js) errored on an issue in ./packages/api/

Below are the 2 actions.

```
## - name: Lint API package
##  uses: sibiraj-s/action-eslint@v2
##   with:
##     github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
##     eslint-args: '--config ./packages/api/.eslintrc.js --ignore-path=.gitignore --quiet'
##     extensions: 'js,mjs'
##     annotations: true
- name: Lint UI package
   uses: sibiraj-s/action-eslint@v2
   with:
     github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
     eslint-args: '--config ./packages/ui/.eslintrc.js --ignore-path=.gitignore --quiet'
     extensions: 'js,mjs,jsx,ts,tsx,vue'
     annotations: true
```
